version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - payment-service
      - inventory-service
      - shipping-service
    volumes:
      - ./api-gateway:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://product-service:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0=Path=/api/products/**
      - SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://payment-service:8082
      - SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0=Path=/api/payments/**
      - SPRING_CLOUD_GATEWAY_ROUTES_2_URI=http://inventory-service:8083
      - SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0=Path=/api/inventory/**
      - SPRING_CLOUD_GATEWAY_ROUTES_3_URI=http://shipping-service:8084
      - SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0=Path=/api/shipping/**

  # Product Service
  product-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8081:8081"
    depends_on:
      - product-db
      - kafka
    volumes:
      - ./product-service:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://product-db:3306/productdb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  product-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productdb
    ports:
      - "3306:3306"
    volumes:
      - product-db-data:/var/lib/mysql

  # Payment Service
  payment-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8082:8082"
    depends_on:
      - payment-db
      - kafka
    volumes:
      - ./payment-service:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://payment-db:3306/paymentdb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  payment-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=paymentdb
    ports:
      - "3307:3306"
    volumes:
      - payment-db-data:/var/lib/mysql

  # Inventory Service
  inventory-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8083:8083"
    depends_on:
      - inventory-db
      - kafka
    volumes:
      - ./inventory-service:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://inventory-db:3306/inventorydb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  inventory-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventorydb
    ports:
      - "3308:3306"
    volumes:
      - inventory-db-data:/var/lib/mysql

  # Shipping Service
  shipping-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8084:8084"
    depends_on:
      - shipping-db
      - kafka
    volumes:
      - ./shipping-service:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://shipping-db:3306/shippingdb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  shipping-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shippingdb
    ports:
      - "3309:3306"
    volumes:
      - shipping-db-data:/var/lib/mysql
  
  # Kafka for messaging
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  product-db-data:
  payment-db-data:
  inventory-db-data:
  shipping-db-data: 