server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://product-db:3306/productdb
    username: root
    password: sapassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org.springframework: INFO
    com.ecommerce: DEBUG 